query {
  pages: allBlogPost(perPage: 5) @paginate {
    totalCount
    pageInfo {
      totalItems
      hasPreviousPage
      hasNextPage
      isFirst
      isLast
      totalPages
      currentPage
    }
    edges {
      node {
        id
        path
        fileInfo {
          path
          name
          extension
          directory
        }
        title
        description
        slug
      }
    }
  }
}
